# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: pre-commit-run-hpack
    name: Generates .cabal files with hpack
    always_run: true
    verbose: true
    stages: [commit]
    language: system
    pass_filenames: false
    entry: hpack
