name:                raytracing
version:             0.1.0.0
github:              "githubuser/raytracing"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/raytracing#readme>

dependencies:
- base >= 4.7 && < 5
- adjunctions
- bytestring
- bytestring-trie
- distributive
- dlist
- fmlist
- foldl
- generic-lens
- hybrid-vectors
- integer-roots
- lens
- linear
- massiv
- massiv-io
- mmorph
- optparse-applicative
- profunctors
- random
- rio
- rio-orphans
- semigroups
- strict
- transformers
- vector
- vector-algorithms
- vector-th-unbox

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  blue-to-white:
    main:                blue-to-white.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing

  gradient-with-simple-sphere:
    main:                gradient-with-simple-sphere.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing

  spheres:
    main:                spheres.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing

  spheres-antialias:
    main:                spheres-antialias.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing

  diffuse:
    main:                diffuse.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing

  metal-spheres:
    main:                metal-spheres.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing

  metals-and-glasses:
    main:                metals-and-glasses.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing

  camera:
    main:                camera.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing
    - scientific

  one-weekend-finale:
    main:                one-weekend-finale.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing
    - scientific

  next-week:
    main:                next-week.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - raytracing
    - scientific

tests:
  raytracing-test:
    main:                Spec.hs
    source-dirs:         test
    build-tools:
    - tasty-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytracing
    - tasty
    - tasty-inspection-testing
